"""协议和具体玩法无关的组织与社会关系底座。"""

SOCIAL_FOUNDATION_VERSION = "social.foundation.v1"

from .engine import SocialEngine
from .models import (
    DISSOLVE_PERMISSION,
    MANAGE_MEMBERS_PERMISSION,
    MANAGE_ROLES_PERMISSION,
    AddOrganizationContribution,
    AdjustSocialRelation,
    ChangeOrganizationRole,
    CreateOrganization,
    CreateSocialRequest,
    DissolveOrganization,
    JoinOrganization,
    LeaveOrganization,
    Organization,
    OrganizationMember,
    OrganizationRoleDefinition,
    OrganizationStatus,
    OrganizationTypeDefinition,
    RelationOverflowPolicy,
    RelationTypeDefinition,
    ResolveSocialRequest,
    SocialCatalog,
    SocialCommand,
    SocialExecution,
    SocialRelation,
    SocialRequest,
    SocialRequestDefinition,
    SocialRequestStatus,
    SocialState,
    TransferOrganizationLeadership,
    relation_key,
)

__all__ = [
    "SOCIAL_FOUNDATION_VERSION",
    "DISSOLVE_PERMISSION",
    "MANAGE_MEMBERS_PERMISSION",
    "MANAGE_ROLES_PERMISSION",
    "AddOrganizationContribution",
    "AdjustSocialRelation",
    "ChangeOrganizationRole",
    "CreateOrganization",
    "CreateSocialRequest",
    "DissolveOrganization",
    "JoinOrganization",
    "LeaveOrganization",
    "Organization",
    "OrganizationMember",
    "OrganizationRoleDefinition",
    "OrganizationStatus",
    "OrganizationTypeDefinition",
    "RelationOverflowPolicy",
    "RelationTypeDefinition",
    "ResolveSocialRequest",
    "SocialCatalog",
    "SocialCommand",
    "SocialEngine",
    "SocialExecution",
    "SocialRelation",
    "SocialRequest",
    "SocialRequestDefinition",
    "SocialRequestStatus",
    "SocialState",
    "TransferOrganizationLeadership",
    "relation_key",
]
