"""魔法世界世界皮肤入口。"""

from .skin import MAGIC_SKIN, MAGIC_SKIN_ID, MAGIC_SKIN_VERSION
from .presentation import MAGIC_ENEMY_PRESENTATION, MAGIC_GEAR_PRESENTATION


__all__ = [
    "MAGIC_ENEMY_PRESENTATION",
    "MAGIC_GEAR_PRESENTATION",
    "MAGIC_SKIN",
    "MAGIC_SKIN_ID",
    "MAGIC_SKIN_VERSION",
]
