"""《万象行纪》的稳定玩家品牌文本。"""


GAME_NAME = "万象行纪"
GAME_TITLE = f"《{GAME_NAME}》"
GAME_TAGLINE = "诸界没有尽头，而你的行纪从第一次降临开始。"
COVENANT_NAME = "归航公约"
COVENANT_MEMBER_NAME = "归航者"
COVENANT_MARKET_NAME = "归航市场"
COVENANT_RECYCLING_NAME = "归航回收"
COVENANT_TREASURY_NAME = "归航库"


__all__ = [
    "COVENANT_MARKET_NAME",
    "COVENANT_MEMBER_NAME",
    "COVENANT_NAME",
    "COVENANT_RECYCLING_NAME",
    "COVENANT_TREASURY_NAME",
    "GAME_NAME",
    "GAME_TAGLINE",
    "GAME_TITLE",
]
