"""官方稳定名录入口；分类定义由 package 模块统一汇总。"""

from .base import (
    COMMON_QUALITY_ID,
    PRIMARY_CURRENCY_ID,
    STANDARD_COMBAT_PROFILE_ID,
)
from .package import CATALOG_PACKAGE, CATALOG_PACKAGE_ID
from .characters import (
    BASIC_COMBAT_FEATURE_ID,
    CHARACTER_LEVEL_EXPERIENCE_REQUIREMENTS,
    CHARACTER_LEVEL_PROGRESSION_ID,
    DEFAULT_CHARACTER_TEMPLATE_ID,
    MORTAL_PHYSIQUE_FEATURE_ID,
    ORIGIN_HUMAN_FEATURE_ID,
)
from .combat import (
    BASIC_ATTACK_ABILITY_ID,
    BREAKING_STRIKE_ABILITY_ID,
    PHYSICAL_DAMAGE_ID,
    SMALL_HEALTH_MEDICINE_ABILITY_ID,
    SMALL_SPIRIT_MEDICINE_ABILITY_ID,
)
from .items import (
    SMALL_HEALTH_MEDICINE_ITEM_ID,
    SMALL_SPIRIT_MEDICINE_ITEM_ID,
    STARTER_WEAPON_ITEM_ID,
)
from .weapons import STARTER_WEAPON_ID
from .world import (
    CHARACTER_PRESENCE_KIND_ID,
    PRIMARY_WORLD_SPACE_ID,
    STARTING_CITY_ID,
    coordinate_token,
    validate_location_coordinate_id,
)


__all__ = [
    "CATALOG_PACKAGE",
    "CATALOG_PACKAGE_ID",
    "BASIC_ATTACK_ABILITY_ID",
    "BASIC_COMBAT_FEATURE_ID",
    "BREAKING_STRIKE_ABILITY_ID",
    "CHARACTER_LEVEL_EXPERIENCE_REQUIREMENTS",
    "CHARACTER_LEVEL_PROGRESSION_ID",
    "CHARACTER_PRESENCE_KIND_ID",
    "COMMON_QUALITY_ID",
    "DEFAULT_CHARACTER_TEMPLATE_ID",
    "MORTAL_PHYSIQUE_FEATURE_ID",
    "ORIGIN_HUMAN_FEATURE_ID",
    "PHYSICAL_DAMAGE_ID",
    "PRIMARY_CURRENCY_ID",
    "PRIMARY_WORLD_SPACE_ID",
    "SMALL_HEALTH_MEDICINE_ABILITY_ID",
    "SMALL_HEALTH_MEDICINE_ITEM_ID",
    "SMALL_SPIRIT_MEDICINE_ABILITY_ID",
    "SMALL_SPIRIT_MEDICINE_ITEM_ID",
    "STANDARD_COMBAT_PROFILE_ID",
    "STARTER_WEAPON_ID",
    "STARTER_WEAPON_ITEM_ID",
    "STARTING_CITY_ID",
    "coordinate_token",
    "validate_location_coordinate_id",
]
