"""基础战斗名录的稳定入口。"""

from .definitions import (
    BASIC_ATTACK_ABILITY_ID,
    BREAKING_STRIKE_ABILITY_ID,
    LARGE_HEALTH_MEDICINE_ABILITY_ID,
    LARGE_MEDICINE_RECOVERY_RATIO,
    LARGE_SPIRIT_MEDICINE_ABILITY_ID,
    MEDIUM_HEALTH_MEDICINE_ABILITY_ID,
    MEDIUM_MEDICINE_RECOVERY_RATIO,
    MEDIUM_SPIRIT_MEDICINE_ABILITY_ID,
    SMALL_HEALTH_MEDICINE_ABILITY_ID,
    SMALL_MEDICINE_RECOVERY_RATIO,
    SMALL_SPIRIT_MEDICINE_ABILITY_ID,
)
from .stats import PHYSICAL_DAMAGE_ID


__all__ = [name for name in globals() if not name.startswith("_")]
