"""基础战斗名录的稳定入口。"""

from .definitions import (
    BASIC_ATTACK_ABILITY_ID,
    BREAKING_STRIKE_ABILITY_ID,
    LARGE_HEALTH_MEDICINE_ABILITY_ID,
    LARGE_MEDICINE_RECOVERY_RATIO,
    LARGE_SPIRIT_MEDICINE_ABILITY_ID,
    MEDIUM_HEALTH_MEDICINE_ABILITY_ID,
    MEDIUM_MEDICINE_RECOVERY_RATIO,
    MEDIUM_SPIRIT_MEDICINE_ABILITY_ID,
    SMALL_HEALTH_MEDICINE_ABILITY_ID,
    SMALL_MEDICINE_RECOVERY_RATIO,
    SMALL_SPIRIT_MEDICINE_ABILITY_ID,
)
from .stats import (
    COMBAT_ACCURACY,
    COMBAT_BLOCK_CHANCE,
    COMBAT_BLOCK_REDUCTION,
    COMBAT_CONTROL_CHANCE,
    COMBAT_CONTROL_RESISTANCE,
    COMBAT_CRITICAL_CHANCE,
    COMBAT_CRITICAL_DAMAGE,
    COMBAT_EVASION,
    COMBAT_FLAT_PENETRATION,
    COMBAT_HEALING_RATE,
    COMBAT_HEALING_RECEIVED,
    COMBAT_INCOMING_RATE,
    COMBAT_OUTGOING_RATE,
    COMBAT_RATE_PENETRATION,
    COMBAT_TENACITY,
    PHYSICAL_DAMAGE_ID,
)


__all__ = [name for name in globals() if not name.startswith("_")]
