"""社会互动内容名录。"""

from game.core.gameplay import PartyDefinition, SocialRequestDefinition


SPARRING_REQUEST_ID = "social_request.sparring"
SPARRING_REQUEST_LIFETIME_SECONDS = 600
SPARRING_REQUEST = SocialRequestDefinition(
    SPARRING_REQUEST_ID,
    SPARRING_REQUEST_LIFETIME_SECONDS,
)

PARTY_INVITATION_REQUEST_ID = "social_request.party_invitation"
PARTY_INVITATION_REQUEST_LIFETIME_SECONDS = 600
PARTY_INVITATION_REQUEST = SocialRequestDefinition(
    PARTY_INVITATION_REQUEST_ID,
    PARTY_INVITATION_REQUEST_LIFETIME_SECONDS,
)

PARTY_TYPE_TRIO_ID = "party_type.trio"
PARTY_TYPE_TRIO = PartyDefinition(PARTY_TYPE_TRIO_ID, 3)

PARTY_BATTLE_MINIMUM_MEMBERS = 2
PARTY_BATTLE_DAILY_REWARD_WINS = 2
PARTY_BATTLE_DAY_RESET_HOUR = 4
PARTY_BATTLE_MAXIMUM_ROUNDS = 30
PARTY_BATTLE_MAXIMUM_TURNS = 600


__all__ = [
    "SPARRING_REQUEST",
    "SPARRING_REQUEST_ID",
    "SPARRING_REQUEST_LIFETIME_SECONDS",
    "PARTY_INVITATION_REQUEST",
    "PARTY_INVITATION_REQUEST_ID",
    "PARTY_INVITATION_REQUEST_LIFETIME_SECONDS",
    "PARTY_TYPE_TRIO",
    "PARTY_TYPE_TRIO_ID",
    "PARTY_BATTLE_MINIMUM_MEMBERS",
    "PARTY_BATTLE_DAILY_REWARD_WINS",
    "PARTY_BATTLE_DAY_RESET_HOUR",
    "PARTY_BATTLE_MAXIMUM_ROUNDS",
    "PARTY_BATTLE_MAXIMUM_TURNS",
]
