"""角色身份、成长和规则实体投影底座。"""

CHARACTER_FOUNDATION_VERSION = "character.foundation.v5"

from .contributions import (
    AttributeGrant,
    CharacterContribution,
    CharacterFeatureDefinition,
    ContributionSpec,
    merge_contribution_specs,
)
from .definitions import (
    CharacterCatalog,
    CharacterTemplateDefinition,
    ProgressionDefinition,
    ProgressionMilestone,
    core_attribute_definitions,
    persistent_resource_definitions,
)
from .models import (
    COMBAT_ATTACK,
    COMBAT_DEFENSE,
    COMBAT_SPEED,
    CORE_ATTRIBUTE_IDS,
    CharacterRosterState,
    CharacterState,
    CharacterStatus,
    HEALTH_CURRENT,
    HEALTH_MAXIMUM,
    MAX_CHARACTER_NAME_LENGTH,
    PERSISTENT_RESOURCE_IDS,
    ProgressionState,
    SPIRIT_CURRENT,
    SPIRIT_MAXIMUM,
    character_name_display_width,
    normalize_character_name,
)
from .projection import CharacterProjection, CharacterProjector
from .items import (
    CHARACTER_EXPERIENCE_ITEM_COMPONENT_ID,
    CharacterExperienceItemComponent,
    CharacterItemUseCommand,
    CharacterItemUseReceipt,
    character_item_use_fingerprint,
)
from .transactions import (
    ChangeCharacterResource,
    CharacterEngine,
    CharacterExecution,
    CharacterOperation,
    CharacterTransaction,
    GrantCoreAttribute,
    GrantExperience,
    RetireCharacter,
    UnlockFeature,
    UnlockProgression,
    UnlockProgressionCap,
)

__all__ = [
    "AttributeGrant",
    "CHARACTER_FOUNDATION_VERSION",
    "COMBAT_ATTACK",
    "COMBAT_DEFENSE",
    "COMBAT_SPEED",
    "CORE_ATTRIBUTE_IDS",
    "CharacterCatalog",
    "CharacterContribution",
    "CharacterFeatureDefinition",
    "CharacterEngine",
    "CharacterExecution",
    "CharacterOperation",
    "CharacterProjection",
    "CharacterProjector",
    "CharacterRosterState",
    "CharacterState",
    "CharacterStatus",
    "CharacterTemplateDefinition",
    "CHARACTER_EXPERIENCE_ITEM_COMPONENT_ID",
    "CharacterExperienceItemComponent",
    "CharacterItemUseCommand",
    "CharacterItemUseReceipt",
    "CharacterTransaction",
    "ChangeCharacterResource",
    "ContributionSpec",
    "HEALTH_CURRENT",
    "HEALTH_MAXIMUM",
    "MAX_CHARACTER_NAME_LENGTH",
    "PERSISTENT_RESOURCE_IDS",
    "ProgressionDefinition",
    "ProgressionMilestone",
    "ProgressionState",
    "GrantCoreAttribute",
    "GrantExperience",
    "RetireCharacter",
    "SPIRIT_CURRENT",
    "SPIRIT_MAXIMUM",
    "UnlockFeature",
    "UnlockProgression",
    "UnlockProgressionCap",
    "core_attribute_definitions",
    "character_name_display_width",
    "persistent_resource_definitions",
    "merge_contribution_specs",
    "normalize_character_name",
    "character_item_use_fingerprint",
]
