"""单武器槽的品质、等级、经验和核心战斗贡献。"""

WEAPON_FOUNDATION_VERSION = "weapon.foundation.v4"

from .models import (
    WeaponCatalog,
    WeaponDefinition,
    WeaponLevelAttribute,
    WeaponMaximumLevelBand,
    WeaponMaximumLevelRoll,
    WeaponMaximumLevelTable,
    WeaponQualityProfile,
    WeaponState,
    WEAPON_ABSOLUTE_MAXIMUM_LEVEL,
    WEAPON_STATE_DATA_KEY,
    weapon_state_data,
    weapon_state_from_data,
    weapon_state_from_instance,
    weapon_level_contribution,
)
from .runtime import (
    WeaponContributionProvider,
    WeaponEngine,
    WeaponExecution,
    WeaponExperienceTransaction,
    WeaponMaximumLevelTransaction,
)
from .items import (
    WEAPON_LEVEL_ITEM_COMPONENT_ID,
    WEAPON_LEVEL_ITEM_COMPONENT_TYPE,
    WEAPON_MAXIMUM_LEVEL_ITEM_COMPONENT_ID,
    WEAPON_MAXIMUM_LEVEL_ITEM_COMPONENT_TYPE,
    WeaponLevelItemComponent,
    WeaponMaximumLevelItemComponent,
    WeaponItemUseCommand,
    WeaponItemUseReceipt,
    weapon_item_use_fingerprint,
)

__all__ = [
    "WEAPON_FOUNDATION_VERSION",
    "WeaponCatalog",
    "WeaponContributionProvider",
    "WeaponDefinition",
    "WeaponEngine",
    "WeaponExecution",
    "WeaponExperienceTransaction",
    "WeaponMaximumLevelTransaction",
    "WeaponLevelAttribute",
    "WeaponMaximumLevelBand",
    "WeaponMaximumLevelRoll",
    "WeaponMaximumLevelTable",
    "WeaponQualityProfile",
    "WeaponState",
    "WEAPON_ABSOLUTE_MAXIMUM_LEVEL",
    "WEAPON_LEVEL_ITEM_COMPONENT_ID",
    "WEAPON_LEVEL_ITEM_COMPONENT_TYPE",
    "WEAPON_MAXIMUM_LEVEL_ITEM_COMPONENT_ID",
    "WEAPON_MAXIMUM_LEVEL_ITEM_COMPONENT_TYPE",
    "WEAPON_STATE_DATA_KEY",
    "WeaponLevelItemComponent",
    "WeaponMaximumLevelItemComponent",
    "WeaponItemUseCommand",
    "WeaponItemUseReceipt",
    "weapon_item_use_fingerprint",
    "weapon_state_data",
    "weapon_state_from_data",
    "weapon_state_from_instance",
    "weapon_level_contribution",
]
