"""跨组件复用的具体游戏规则。"""

from .activity import (
    GLOBAL_ACTIVITY_SCOPE_ID,
    ActivitySpotlightPolicy,
    GlobalActivityCatalog,
    GlobalActivityRegistration,
    GlobalActivityPresentation,
    GlobalActivitySelection,
    GlobalActivityView,
    global_activity_catalog,
    register_global_activity,
    resolve_global_activity_presentation,
)
from .character import (
    CHARACTER_CREATION_PROTOCOL_VERSION,
    CHARACTER_SETTINGS_AGGREGATE,
    CharacterCreationIds,
    CharacterCreationPlan,
    CharacterCreationPlanner,
    CharacterCreationReceipt,
    CharacterCreationRequest,
    CharacterCreationViolation,
    CharacterCreationWorkflow,
    character_creation_context,
    CharacterIdentityPolicy,
    CharacterIdentityViolation,
    CharacterNameSource,
    CharacterSettingsState,
    PRIMARY_ISSUER_ACCOUNT_ID,
    PRIMARY_LEDGER_ID,
    PRIMARY_WORLD_ID,
    PreparedCharacterIdentity,
)
from .combat import PlayerCombatProjector
from .equipment import (
    EQUIPMENT_GENERATION_PROTOCOL_VERSION,
    EquipmentGenerationRequest,
    EquipmentGenerationResult,
    EquipmentInstanceGenerator,
)
from .encounter import (
    EnemyDefeatRewardPlanner,
    EnemyDefeatRewardQuote,
    EnemyEncounterGenerator,
    EnemyLootQuote,
)
from .weapon import (
    WEAPON_GENERATION_PROTOCOL_VERSION,
    WeaponGenerationRequest,
    WeaponGenerationResult,
    WeaponInstanceGenerator,
)
from .context import GAME_OPERATION_RULE_VERSION, game_operation_context
from .disaster import (
    DIMENSIONAL_DISASTER_AGGREGATE,
    DIMENSIONAL_DISASTER_RULESET_VERSION,
    DimensionalDisasterOutcome,
    DimensionalDisasterState,
    DimensionalDisasterStatus,
    DisasterChallengeReceipt,
    DisasterCombatSnapshot,
    DisasterNarrativeSnapshot,
    begin_disaster_settlement,
    close_disaster,
    mark_disaster_rewarded,
    record_disaster_challenge,
)


__all__ = [
    "ActivitySpotlightPolicy",
    "CHARACTER_CREATION_PROTOCOL_VERSION",
    "CHARACTER_SETTINGS_AGGREGATE",
    "CharacterCreationIds",
    "CharacterCreationPlan",
    "CharacterCreationPlanner",
    "CharacterCreationReceipt",
    "CharacterCreationRequest",
    "CharacterCreationViolation",
    "CharacterCreationWorkflow",
    "character_creation_context",
    "CharacterIdentityPolicy",
    "CharacterIdentityViolation",
    "CharacterNameSource",
    "CharacterSettingsState",
    "DIMENSIONAL_DISASTER_AGGREGATE",
    "DIMENSIONAL_DISASTER_RULESET_VERSION",
    "DimensionalDisasterOutcome",
    "DimensionalDisasterState",
    "DimensionalDisasterStatus",
    "DisasterChallengeReceipt",
    "DisasterCombatSnapshot",
    "DisasterNarrativeSnapshot",
    "EQUIPMENT_GENERATION_PROTOCOL_VERSION",
    "EquipmentGenerationRequest",
    "EquipmentGenerationResult",
    "EquipmentInstanceGenerator",
    "EnemyDefeatRewardPlanner",
    "EnemyDefeatRewardQuote",
    "EnemyEncounterGenerator",
    "EnemyLootQuote",
    "WEAPON_GENERATION_PROTOCOL_VERSION",
    "WeaponGenerationRequest",
    "WeaponGenerationResult",
    "WeaponInstanceGenerator",
    "GLOBAL_ACTIVITY_SCOPE_ID",
    "GAME_OPERATION_RULE_VERSION",
    "GlobalActivityCatalog",
    "GlobalActivityRegistration",
    "GlobalActivityPresentation",
    "GlobalActivitySelection",
    "GlobalActivityView",
    "PRIMARY_ISSUER_ACCOUNT_ID",
    "PRIMARY_LEDGER_ID",
    "PRIMARY_WORLD_ID",
    "PreparedCharacterIdentity",
    "PlayerCombatProjector",
    "global_activity_catalog",
    "game_operation_context",
    "begin_disaster_settlement",
    "close_disaster",
    "mark_disaster_rewarded",
    "record_disaster_challenge",
    "register_global_activity",
    "resolve_global_activity_presentation",
]
