"""正式敌人内容领域入口。"""

from .behaviors import ENEMY_BEHAVIOR_CONTENT
from .blueprints import BEHAVIOR_BLUEPRINTS, BOSS_ENEMY_BLUEPRINTS, REGULAR_ENEMY_BLUEPRINTS
from .definitions import (
    BOSS_ENEMIES,
    ENEMY_DEFINITIONS,
    ENEMY_DEFINITION_DISPLAY_IDS,
    ENEMY_RANKS,
    ENEMY_RANK_DISPLAY_IDS,
    ENEMY_REWARD_PROFILES,
    REGULAR_ENEMIES,
    STANDARD_ENEMY_LEVEL_PROFILE,
)
from .encounters import ENCOUNTER_DISPLAY_IDS, ENCOUNTER_SCOPES, ENEMY_ENCOUNTERS
from .loot import ENEMY_LOOT_TABLES


ENEMY_DISPLAY_CONTENT_IDS = (
    ENEMY_BEHAVIOR_CONTENT.display_ids
    | ENEMY_DEFINITION_DISPLAY_IDS
    | ENEMY_RANK_DISPLAY_IDS
    | ENCOUNTER_DISPLAY_IDS
)


__all__ = [
    "BEHAVIOR_BLUEPRINTS",
    "BOSS_ENEMIES",
    "BOSS_ENEMY_BLUEPRINTS",
    "ENCOUNTER_SCOPES",
    "ENEMY_BEHAVIOR_CONTENT",
    "ENEMY_DEFINITIONS",
    "ENEMY_DISPLAY_CONTENT_IDS",
    "ENEMY_ENCOUNTERS",
    "ENEMY_LOOT_TABLES",
    "ENEMY_RANKS",
    "ENEMY_REWARD_PROFILES",
    "REGULAR_ENEMIES",
    "REGULAR_ENEMY_BLUEPRINTS",
    "STANDARD_ENEMY_LEVEL_PROFILE",
]
