"""正式敌人内容领域入口。"""

from .behaviors import ENEMY_BEHAVIOR_CONTENT
from .blueprints import (
    BEHAVIOR_BLUEPRINTS,
    CULTIVATION_PARTY_BOSS_BLUEPRINTS,
    MAGIC_PARTY_BOSS_BLUEPRINTS,
    PARTY_BOSS_BLUEPRINTS,
    PERSONAL_BOSS_BLUEPRINTS,
    REGULAR_ENEMY_BLUEPRINTS,
)
from .definitions import (
    ENEMY_DEFINITIONS,
    ENEMY_DEFINITION_DISPLAY_IDS,
    ENEMY_RANKS,
    ENEMY_RANK_DISPLAY_IDS,
    ENEMY_REWARD_PROFILES,
    PERSONAL_BOSS_ENEMIES,
    REGULAR_ENEMIES,
    STANDARD_ENEMY_LEVEL_PROFILE,
)
from .party import (
    CULTIVATION_PARTY_BOSS_ENEMIES,
    MAGIC_PARTY_BOSS_ENEMIES,
    PARTY_BOSS_DISPLAY_IDS,
    PARTY_BOSS_ENEMIES,
    PARTY_BOSS_LEVEL_PROFILE,
    PARTY_BOSS_REWARD_PROFILE,
    PARTY_BOSS_SOURCE_CATALOG,
    PartyBossSourceCatalog,
    PartyBossSourceDefinition,
)
from .encounters import (
    ENCOUNTER_DISPLAY_IDS,
    ENCOUNTER_SCOPES,
    ENEMY_ENCOUNTERS,
    PARTY_BOSS_ENCOUNTER_ID,
    PERSONAL_BOSS_ENCOUNTER_ID,
    PERSONAL_ELITE_ENCOUNTER_ID,
    PERSONAL_NORMAL_ENCOUNTER_ID,
)
from .loot import (
    AWARD_BOSS_TROPHY_ID,
    AWARD_PARTY_BOSS_TROPHY_ID,
    AWARD_DRAW_TICKET_ID,
    AWARD_ENEMY_TROPHY_ID,
    AWARD_LARGE_HEALTH_MEDICINE_ID,
    AWARD_LARGE_SPIRIT_MEDICINE_ID,
    AWARD_MEDIUM_HEALTH_MEDICINE_ID,
    AWARD_MEDIUM_SPIRIT_MEDICINE_ID,
    AWARD_RANDOM_EQUIPMENT_ID,
    AWARD_RANDOM_WEAPON_ID,
    AWARD_REGION_TROPHY_ID,
    AWARD_SMALL_HEALTH_MEDICINE_ID,
    AWARD_SMALL_SPIRIT_MEDICINE_ID,
    AWARD_WORLD_CURIO_ID,
    ENEMY_LOOT_TABLES,
    PARTY_BOSS_LOOT_TABLE_ID,
)


ENEMY_DISPLAY_CONTENT_IDS = (
    ENEMY_BEHAVIOR_CONTENT.display_ids
    | ENEMY_DEFINITION_DISPLAY_IDS
    | PARTY_BOSS_DISPLAY_IDS
    | ENEMY_RANK_DISPLAY_IDS
    | ENCOUNTER_DISPLAY_IDS
)


__all__ = [
    "AWARD_BOSS_TROPHY_ID",
    "AWARD_PARTY_BOSS_TROPHY_ID",
    "AWARD_DRAW_TICKET_ID",
    "AWARD_ENEMY_TROPHY_ID",
    "AWARD_LARGE_HEALTH_MEDICINE_ID",
    "AWARD_LARGE_SPIRIT_MEDICINE_ID",
    "AWARD_MEDIUM_HEALTH_MEDICINE_ID",
    "AWARD_MEDIUM_SPIRIT_MEDICINE_ID",
    "BEHAVIOR_BLUEPRINTS",
    "AWARD_RANDOM_EQUIPMENT_ID",
    "AWARD_RANDOM_WEAPON_ID",
    "AWARD_REGION_TROPHY_ID",
    "AWARD_SMALL_HEALTH_MEDICINE_ID",
    "AWARD_SMALL_SPIRIT_MEDICINE_ID",
    "AWARD_WORLD_CURIO_ID",
    "CULTIVATION_PARTY_BOSS_BLUEPRINTS",
    "CULTIVATION_PARTY_BOSS_ENEMIES",
    "ENCOUNTER_SCOPES",
    "ENEMY_BEHAVIOR_CONTENT",
    "ENEMY_DEFINITIONS",
    "ENEMY_DISPLAY_CONTENT_IDS",
    "ENEMY_ENCOUNTERS",
    "ENEMY_LOOT_TABLES",
    "ENEMY_RANKS",
    "ENEMY_REWARD_PROFILES",
    "MAGIC_PARTY_BOSS_BLUEPRINTS",
    "MAGIC_PARTY_BOSS_ENEMIES",
    "PARTY_BOSS_BLUEPRINTS",
    "PARTY_BOSS_ENEMIES",
    "PARTY_BOSS_ENCOUNTER_ID",
    "PARTY_BOSS_LEVEL_PROFILE",
    "PARTY_BOSS_LOOT_TABLE_ID",
    "PARTY_BOSS_REWARD_PROFILE",
    "PARTY_BOSS_SOURCE_CATALOG",
    "PERSONAL_BOSS_BLUEPRINTS",
    "PERSONAL_BOSS_ENEMIES",
    "PERSONAL_BOSS_ENCOUNTER_ID",
    "PERSONAL_ELITE_ENCOUNTER_ID",
    "PERSONAL_NORMAL_ENCOUNTER_ID",
    "REGULAR_ENEMIES",
    "REGULAR_ENEMY_BLUEPRINTS",
    "STANDARD_ENEMY_LEVEL_PROFILE",
    "PartyBossSourceCatalog",
    "PartyBossSourceDefinition",
]
