"""正式敌人内容领域入口。"""

from .behaviors import ENEMY_BEHAVIOR_CONTENT
from .blueprints import BEHAVIOR_BLUEPRINTS, BOSS_ENEMY_BLUEPRINTS, REGULAR_ENEMY_BLUEPRINTS
from .definitions import (
    BOSS_ENEMIES,
    ENEMY_DEFINITIONS,
    ENEMY_DEFINITION_DISPLAY_IDS,
    ENEMY_RANKS,
    ENEMY_RANK_DISPLAY_IDS,
    ENEMY_REWARD_PROFILES,
    REGULAR_ENEMIES,
    STANDARD_ENEMY_LEVEL_PROFILE,
)
from .encounters import (
    ENCOUNTER_DISPLAY_IDS,
    ENCOUNTER_SCOPES,
    ENEMY_ENCOUNTERS,
    PERSONAL_BOSS_ENCOUNTER_ID,
    PERSONAL_ELITE_ENCOUNTER_ID,
    PERSONAL_NORMAL_ENCOUNTER_ID,
)
from .loot import (
    AWARD_BOSS_TROPHY_ID,
    AWARD_ENEMY_TROPHY_ID,
    AWARD_LARGE_HEALTH_MEDICINE_ID,
    AWARD_LARGE_SPIRIT_MEDICINE_ID,
    AWARD_MEDIUM_HEALTH_MEDICINE_ID,
    AWARD_MEDIUM_SPIRIT_MEDICINE_ID,
    AWARD_RANDOM_EQUIPMENT_ID,
    AWARD_RANDOM_WEAPON_ID,
    AWARD_REGION_TROPHY_ID,
    AWARD_SMALL_HEALTH_MEDICINE_ID,
    AWARD_SMALL_SPIRIT_MEDICINE_ID,
    AWARD_WORLD_CURIO_ID,
    ENEMY_LOOT_TABLES,
)


ENEMY_DISPLAY_CONTENT_IDS = (
    ENEMY_BEHAVIOR_CONTENT.display_ids
    | ENEMY_DEFINITION_DISPLAY_IDS
    | ENEMY_RANK_DISPLAY_IDS
    | ENCOUNTER_DISPLAY_IDS
)


__all__ = [
    "AWARD_BOSS_TROPHY_ID",
    "AWARD_ENEMY_TROPHY_ID",
    "AWARD_LARGE_HEALTH_MEDICINE_ID",
    "AWARD_LARGE_SPIRIT_MEDICINE_ID",
    "AWARD_MEDIUM_HEALTH_MEDICINE_ID",
    "AWARD_MEDIUM_SPIRIT_MEDICINE_ID",
    "BEHAVIOR_BLUEPRINTS",
    "AWARD_RANDOM_EQUIPMENT_ID",
    "AWARD_RANDOM_WEAPON_ID",
    "AWARD_REGION_TROPHY_ID",
    "AWARD_SMALL_HEALTH_MEDICINE_ID",
    "AWARD_SMALL_SPIRIT_MEDICINE_ID",
    "AWARD_WORLD_CURIO_ID",
    "BOSS_ENEMIES",
    "BOSS_ENEMY_BLUEPRINTS",
    "ENCOUNTER_SCOPES",
    "ENEMY_BEHAVIOR_CONTENT",
    "ENEMY_DEFINITIONS",
    "ENEMY_DISPLAY_CONTENT_IDS",
    "ENEMY_ENCOUNTERS",
    "ENEMY_LOOT_TABLES",
    "ENEMY_RANKS",
    "ENEMY_REWARD_PROFILES",
    "PERSONAL_BOSS_ENCOUNTER_ID",
    "PERSONAL_ELITE_ENCOUNTER_ID",
    "PERSONAL_NORMAL_ENCOUNTER_ID",
    "REGULAR_ENEMIES",
    "REGULAR_ENEMY_BLUEPRINTS",
    "STANDARD_ENEMY_LEVEL_PROFILE",
]
