"""归航兑换使用的稳定价值锚与套装图纸价格。"""

from __future__ import annotations


EXCHANGE_MATERIAL_REFERENCE_VALUE = 50
# 由正式 9216 样本装备审计的平均参考价 2500.88 校准。
EQUIPMENT_BLUEPRINT_EXPECTED_GEAR_VALUE = 2_500
EQUIPMENT_BLUEPRINT_TARGETING_PREMIUM_BPS = 2_500
EQUIPMENT_SET_BLUEPRINT_PRICE = (
    EQUIPMENT_BLUEPRINT_EXPECTED_GEAR_VALUE
    * (10_000 + EQUIPMENT_BLUEPRINT_TARGETING_PREMIUM_BPS)
    + EXCHANGE_MATERIAL_REFERENCE_VALUE * 10_000
    - 1
) // (EXCHANGE_MATERIAL_REFERENCE_VALUE * 10_000)


__all__ = [
    "EQUIPMENT_BLUEPRINT_EXPECTED_GEAR_VALUE",
    "EQUIPMENT_BLUEPRINT_TARGETING_PREMIUM_BPS",
    "EQUIPMENT_SET_BLUEPRINT_PRICE",
    "EXCHANGE_MATERIAL_REFERENCE_VALUE",
]
