"""彩票系统的正式平衡参数。"""

LOTTERY_TICKET_PRICE = 20
LOTTERY_MIN_PARTICIPANTS = 2
LOTTERY_CENTRAL_SUBSIDY_RATE = 0.20
LOTTERY_CENTRAL_SUBSIDY_MULTIPLIER = 4
LOTTERY_POOL_MAX = 20_000
LOTTERY_MIN_PRIZE = 1

__all__ = [
    "LOTTERY_CENTRAL_SUBSIDY_MULTIPLIER",
    "LOTTERY_CENTRAL_SUBSIDY_RATE",
    "LOTTERY_MIN_PRIZE",
    "LOTTERY_MIN_PARTICIPANTS",
    "LOTTERY_POOL_MAX",
    "LOTTERY_TICKET_PRICE",
]
