"""正式经济政策参数；规则层只读取，不在代码流程中散落平衡数字。"""


ECONOMY_POLICY_ID = "economy_policy.primary"
ECONOMY_POLICY_VERSION = 2

GEAR_VALUE_POINT_PRICE = 100
WEAPON_LEVEL_PREMIUM_BPS = 100
WEAPON_MAXIMUM_LEVEL_PREMIUM_BPS = 50
WEAPON_MAXIMUM_LEVEL_PREMIUM_BASE = 20
EQUIPMENT_SET_PREMIUM_BPS = 2_000

GEAR_RECYCLE_RATE_BPS = 2_500

MARKET_BASE_TAX_BPS = 800
MARKET_MIN_PRICE_BPS = 7_000
MARKET_MAX_SELLER_PRICE_BPS = 15_000
MARKET_PAIR_REPEAT_TAX_BPS = 500
MARKET_ASSET_REPEAT_TAX_BPS = 1_000
MARKET_NORMAL_TAX_MAX_BPS = 3_000
MARKET_RISK_WINDOW_SECONDS = 7 * 24 * 60 * 60
MARKET_LISTING_LIFETIME_SECONDS = 7 * 24 * 60 * 60


__all__ = [
    "ECONOMY_POLICY_ID",
    "ECONOMY_POLICY_VERSION",
    "EQUIPMENT_SET_PREMIUM_BPS",
    "GEAR_RECYCLE_RATE_BPS",
    "GEAR_VALUE_POINT_PRICE",
    "MARKET_ASSET_REPEAT_TAX_BPS",
    "MARKET_BASE_TAX_BPS",
    "MARKET_LISTING_LIFETIME_SECONDS",
    "MARKET_MAX_SELLER_PRICE_BPS",
    "MARKET_MIN_PRICE_BPS",
    "MARKET_NORMAL_TAX_MAX_BPS",
    "MARKET_PAIR_REPEAT_TAX_BPS",
    "MARKET_RISK_WINDOW_SECONDS",
    "WEAPON_LEVEL_PREMIUM_BPS",
    "WEAPON_MAXIMUM_LEVEL_PREMIUM_BPS",
    "WEAPON_MAXIMUM_LEVEL_PREMIUM_BASE",
]
