"""太玄界世界皮肤的唯一组装入口。"""

from game.core.gameplay import SkinPack

from .base import CULTIVATION_BASE_ENTRIES
from .character import CULTIVATION_CHARACTER_ENTRIES
from .combat import CULTIVATION_COMBAT_ENTRIES
from .companions import CULTIVATION_COMPANION_ENTRIES
from .equipment import CULTIVATION_EQUIPMENT_ENTRIES
from .enemies import CULTIVATION_ENEMY_ENTRIES
from .items import CULTIVATION_ITEM_ENTRIES
from .trophies import CULTIVATION_TROPHY_ENTRIES
from .weapons import CULTIVATION_WEAPON_ENTRIES
from .world import CULTIVATION_WORLD_ENTRIES


CULTIVATION_SKIN_ID = "skin.cultivation"
CULTIVATION_SKIN_VERSION = 27


CULTIVATION_SKIN = SkinPack(
    id=CULTIVATION_SKIN_ID,
    version=CULTIVATION_SKIN_VERSION,
    name="太玄界",
    icon="☯",
    entries={
        **CULTIVATION_BASE_ENTRIES,
        **CULTIVATION_CHARACTER_ENTRIES,
        **CULTIVATION_COMBAT_ENTRIES,
        **CULTIVATION_COMPANION_ENTRIES,
        **CULTIVATION_EQUIPMENT_ENTRIES,
        **CULTIVATION_ENEMY_ENTRIES,
        **CULTIVATION_ITEM_ENTRIES,
        **CULTIVATION_TROPHY_ENTRIES,
        **CULTIVATION_WEAPON_ENTRIES,
        **CULTIVATION_WORLD_ENTRIES,
    },
)


__all__ = ["CULTIVATION_SKIN", "CULTIVATION_SKIN_ID", "CULTIVATION_SKIN_VERSION"]
