"""人物与成长名录的稳定入口。"""

from .definitions import (
    BASIC_COMBAT_FEATURE_ID,
    CHARACTER_LEVEL_EXPERIENCE_REQUIREMENTS,
    CHARACTER_MAXIMUM_LEVEL,
    CHARACTER_LEVEL_PROGRESSION_ID,
    DEFAULT_CHARACTER_TEMPLATE_ID,
    INITIAL_CORE_ATTRIBUTES,
    LEVEL_CORE_ATTRIBUTE_DELTAS,
    MORTAL_PHYSIQUE_FEATURE_ID,
    ORIGIN_HUMAN_FEATURE_ID,
    character_level_milestone,
    character_level_milestones,
)
from .identity import CHARACTERS_PER_ACCOUNT, MAX_CHARACTER_NAME_DISPLAY_WIDTH
from .recovery import (
    AUTO_HEALTH_TARGET_RATIO,
    AUTO_HEALTH_TRIGGER_RATIO,
    AUTO_SPIRIT_TARGET_RATIO,
    AUTO_SPIRIT_TRIGGER_RATIO,
    REST_FULL_RECOVERY_SECONDS,
    REST_ACTION_DEFINITION,
    REST_ACTION_ID,
    REST_MINIMUM_RECOVERY_RATIO,
    REST_MINIMUM_SECONDS,
)
from .realms import (
    CHARACTER_REALMS,
    CHARACTER_REALM_CONTENT_DEFINITIONS,
    CHARACTER_REALM_DISPLAY_IDS,
    CharacterRealmDefinition,
    character_realm_for_level,
)
from .starting import (
    INITIAL_BACKPACK_CAPACITY,
    INITIAL_CURRENCY_AMOUNT,
    INITIAL_MEDICINE_QUANTITY,
    LOADOUT_PRESET_IDS,
)


__all__ = [name for name in globals() if not name.startswith("_")]
