"""自动用药与休息恢复的统一内容参数。"""

from datetime import timedelta

from game.core.gameplay import ActionDefinition, ActionSlotKind


AUTO_HEALTH_TRIGGER_RATIO = 0.25
AUTO_HEALTH_TARGET_RATIO = 0.55
AUTO_SPIRIT_TRIGGER_RATIO = 0.15
AUTO_SPIRIT_TARGET_RATIO = 0.45
REST_MINIMUM_SECONDS = 60
REST_FULL_RECOVERY_SECONDS = 30 * 60
REST_MINIMUM_RECOVERY_RATIO = 0.50
REST_ACTION_ID = "action.character.rest"
REST_ACTION_DEFINITION = ActionDefinition(
    REST_ACTION_ID,
    ActionSlotKind.MAIN,
    timedelta(seconds=REST_FULL_RECOVERY_SECONDS),
)


__all__ = [
    "AUTO_HEALTH_TARGET_RATIO",
    "AUTO_HEALTH_TRIGGER_RATIO",
    "AUTO_SPIRIT_TARGET_RATIO",
    "AUTO_SPIRIT_TRIGGER_RATIO",
    "REST_FULL_RECOVERY_SECONDS",
    "REST_ACTION_DEFINITION",
    "REST_ACTION_ID",
    "REST_MINIMUM_RECOVERY_RATIO",
    "REST_MINIMUM_SECONDS",
]
