"""太玄界为全服灾厄池贡献的固定灾厄素材。"""

from .models import (
    DISASTER_ORIGIN_DOCUMENTED,
    DISASTER_ORIGIN_ORIGINAL,
    DimensionalDisasterDefinition,
)
from .templates import DISASTER_BEHAVIOR_KEYS_BY_TEMPLATE


CULTIVATION_DISASTER_SOURCE_ID = "skin.cultivation"


def _disaster(
    key: str,
    enemy_key: str,
    origin_kind: str,
    source_note: str,
    name: str,
    title: str,
    scene: str,
    story: str,
    farewell: str,
    feather_text: str,
) -> DimensionalDisasterDefinition:
    return DimensionalDisasterDefinition(
        f"disaster.cultivation.{key}",
        CULTIVATION_DISASTER_SOURCE_ID,
        f"enemy.boss.disaster.cultivation.{key}",
        DISASTER_BEHAVIOR_KEYS_BY_TEMPLATE[enemy_key],
        origin_kind,
        source_note,
        name,
        title,
        scene,
        story,
        farewell,
        feather_text,
    )


CULTIVATION_DISASTERS = (
    _disaster(
        "xiangliu",
        "nine_headed_plague",
        DISASTER_ORIGIN_DOCUMENTED,
        "《山海经·海外北经》相柳传说",
        "相柳·九泉蚀主",
        "九首共饮山河毒脉的古神",
        "九道黑水同时漫过天际，每一片水面都倒映着不同的蛇首。",
        "相柳死后血染大地，所过之处五谷不生。如今九首越过界壁，在诸界水脉中重新睁眼。",
        "九首沉入裂开的黑水，只剩被毒潮啃蚀的星光。",
        "黑水退尽后，一枚带九道蚀纹的铭刻之羽浮在水面，像九个不肯同时闭上的梦。",
    ),
    _disaster(
        "hanba",
        "drought_incarnate",
        DISASTER_ORIGIN_DOCUMENTED,
        "《山海经·大荒北经》女魃传说",
        "旱魃·赤地天女",
        "踏过之处万里无云的灾神",
        "赤发女子从干裂天幕中走出，脚下河床一寸寸化为白灰。",
        "她曾助黄帝止雨，却再也回不到天上。漫长放逐让她成为所有世界共同畏惧的干旱。",
        "第一滴雨穿过她透明的掌心，落进久旱的尘土。",
        "雨声中落下一枚赤白遗羽，羽脉里仍封着一线没有降下的云。",
    ),
    _disaster(
        "wuzhiqi",
        "river_rebel",
        DISASTER_ORIGIN_DOCUMENTED,
        "唐代《古岳渎经》无支祁传说",
        "无支祁·淮涡水君",
        "拖动天下水脉锁链的妖神",
        "一根古老铁索从次元裂隙垂下，索后巨猿挟着整片洪峰撞入诸界。",
        "大禹锁住了它的身躯，却没有锁住水对自由的记忆。每次界壁松动，它都会循水声而来。",
        "铁索重新沉入深渊，翻涌洪峰终于记起河道。",
        "断链旁留下一枚青铜色遗羽，贴近时能听见被压低了千年的水吼。",
    ),
    _disaster(
        "jiuying",
        "venom_world_serpent",
        DISASTER_ORIGIN_DOCUMENTED,
        "《淮南子·本经训》九婴传说",
        "九婴·水火灾主",
        "九声啼哭同时点燃洪水的凶兽",
        "九张巨口悬在裂界之上，一半吐出洪流，一半喷落苍白火雨。",
        "它生于水火交错之地，哭声既是婴啼，也是世界断裂前最后的警告。",
        "最后一声啼哭熄灭，水与火在虚空中彼此吞没。",
        "冷热交替的雾中飘下一枚九孔遗羽，每个孔洞都藏着一声未落地的哭声。",
    ),
    _disaster(
        "zhulong",
        "twilight_dragon",
        DISASTER_ORIGIN_DOCUMENTED,
        "《山海经·大荒北经》烛龙传说",
        "烛九阴·幽明龙祖",
        "睁眼为昼闭目为夜的界外巨龙",
        "一只赤色竖瞳横贯天穹，诸界昼夜在它每次眨眼间失去次序。",
        "钟山之神本不属于任何人间。界相重叠惊醒了它，也令时间第一次看见自己的背面。",
        "巨瞳缓缓闭合，错乱的日夜重新沿各自轨迹流动。",
        "昼夜交界处凝成一枚半明半暗的遗羽，羽面永远停在黄昏前的一瞬。",
    ),
    _disaster(
        "xingtian",
        "headless_warrior",
        DISASTER_ORIGIN_DOCUMENTED,
        "《山海经·海外西经》刑天传说",
        "刑天·不息战魄",
        "失去首级仍向天挥斧的战神",
        "无首巨人踏碎界门，以乳为目、脐为口，干戚每次挥落都斩开新的天痕。",
        "胜负早已结束，战意却拒绝承认结局。它追逐的不是敌人，而是所有世界仍在运转的天。",
        "巨斧落地，胸前双眼终于在寂静中合拢。",
        "斧痕深处升起一枚铁灰遗羽，握住它时，掌心会多出一道不肯愈合的战纹。",
    ),
    _disaster(
        "qiongqi",
        "winged_omen",
        DISASTER_ORIGIN_DOCUMENTED,
        "《山海经》《左传》穷奇传说",
        "穷奇·食忠凶神",
        "以善念为食、替恶者张翼的凶兽",
        "带刺巨翼遮住星路，兽首循着每一缕善意俯冲而下。",
        "它听见争辩便吞食有理者，见到忠信便撕碎其鼻。诸界越是抵抗，它越能尝到勇气。",
        "凶翼折断，所有被吞下的微光从伤口中飞回人间。",
        "散落善念围成一枚墨金遗羽，羽根仍留着凶兽咬合时的裂痕。",
    ),
    _disaster(
        "bridge_lantern",
        "soul_ferryman",
        DISASTER_ORIGIN_ORIGINAL,
        "原创岁时旧愿",
        "旧桥挑灯客",
        "守着一盏照不到归人的旧灯",
        "断桥跨过无数世界，一名提灯人站在桥心，逐一呼唤无人记得的名字。",
        "他等的人早已在另一条时间里老去，只有桥灯仍把那次约定误认成今日。",
        "桥灯熄灭，提灯人向没有尽头的对岸作了最后一揖。",
        "灯穗上落下一枚昏黄铭刻之羽，像一盏照不到亲人的灯。",
    ),
    _disaster(
        "nameless_official",
        "celestial_rebel",
        DISASTER_ORIGIN_ORIGINAL,
        "原创天律灾厄",
        "失名天官",
        "从万界名册中被同时抹去的执笔者",
        "无字天榜铺满虚空，一位没有面目的官吏正把众生姓名逐行划去。",
        "他曾负责记录飞升者，直到发现榜上从没有自己的名字。于是他决定让所有名字一同消失。",
        "无字天榜燃成白灰，执笔者终于写下了自己的最后一画。",
        "纸灰中浮起一枚纯白遗羽，羽轴刻着一个任何文字都无法读出的名字。",
    ),
    _disaster(
        "inverted_mountain",
        "realm_breaker",
        DISASTER_ORIGIN_ORIGINAL,
        "原创界域灾厄",
        "倒悬山主",
        "背负逆山穿行诸界的沉默巨灵",
        "一座山从天外倒悬而下，山尖之后，披石甲的巨灵拖着整条破碎地脉。",
        "它寻找能够承受这座山的世界，每一次停步都会让当地的上下与轻重彻底颠倒。",
        "倒山缓缓升回虚空，散落群峰重新认出大地。",
        "失重尘埃聚成一枚石纹遗羽，放手时它会向天空坠落。",
    ),
)


__all__ = ["CULTIVATION_DISASTERS", "CULTIVATION_DISASTER_SOURCE_ID"]
