"""魔法世界为全服灾厄池贡献的固定灾厄素材。"""

from .models import (
    DISASTER_ORIGIN_DOCUMENTED,
    DISASTER_ORIGIN_ORIGINAL,
    DimensionalDisasterDefinition,
)
from .templates import DISASTER_BEHAVIOR_KEYS_BY_TEMPLATE


MAGIC_DISASTER_SOURCE_ID = "skin.magic"


def _disaster(
    key: str,
    enemy_key: str,
    origin_kind: str,
    source_note: str,
    name: str,
    title: str,
    scene: str,
    story: str,
    farewell: str,
    feather_text: str,
) -> DimensionalDisasterDefinition:
    return DimensionalDisasterDefinition(
        f"disaster.magic.{key}",
        MAGIC_DISASTER_SOURCE_ID,
        f"enemy.boss.disaster.magic.{key}",
        DISASTER_BEHAVIOR_KEYS_BY_TEMPLATE[enemy_key],
        origin_kind,
        source_note,
        name,
        title,
        scene,
        story,
        farewell,
        feather_text,
    )


MAGIC_DISASTERS = (
    _disaster(
        "fenrir",
        "doom_fenrir",
        DISASTER_ORIGIN_DOCUMENTED,
        "《诗体埃达》《散文埃达》芬里尔传说",
        "芬里尔·噬日之狼",
        "挣断诸神锁链的终末巨狼",
        "黑狼衔着残缺太阳跃出裂隙，三种神铁锁链在身后拖过群星。",
        "诸神因恐惧而束缚它，也亲手证明了预言。如今它把每一个世界的太阳都认作同一轮猎物。",
        "狼口松开，伤痕累累的太阳重新照见诸界。",
        "断裂神链间留下一枚暗银遗羽，边缘像被巨齿整齐咬去一角。",
    ),
    _disaster(
        "jormungandr",
        "world_leviathan",
        DISASTER_ORIGIN_DOCUMENTED,
        "北欧神话尘世巨蟒耶梦加得传说",
        "耶梦加得·环界巨蟒",
        "以自身首尾丈量世界边界的巨蛇",
        "无边蛇躯从多处天际同时升起，诸界仿佛都被套进同一个收紧的圆环。",
        "它曾环绕一整个尘世，如今界壁重叠，让它误以为所有宇宙都只是更大的海。",
        "巨环松开，海潮带着破碎鳞光退回世界之外。",
        "一枚深蓝遗羽卡在脱落蛇鳞中，羽面弯曲成永远无法闭合的圆。",
    ),
    _disaster(
        "typhon",
        "storm_dragon",
        DISASTER_ORIGIN_DOCUMENTED,
        "古希腊神话提丰传说",
        "提丰·百首风暴",
        "令奥林匹斯诸神逃亡的群首巨神",
        "无数兽首从雷云中探出，每一种吼声都在另一世界引发风暴。",
        "大地与深渊生下它反抗天空。即使被群山镇压，怒吼仍能沿界缝寻找出口。",
        "百首逐一沉默，最后一道雷在虚空深处折断。",
        "焦黑云絮凝成一枚雷纹遗羽，羽尖仍会在无人触碰时迸出蓝光。",
    ),
    _disaster(
        "leviathan",
        "abyss_kraken",
        DISASTER_ORIGIN_DOCUMENTED,
        "《约伯记》等文献中的利维坦传说",
        "利维坦·深渊王冠",
        "让大海如锅沸腾的古老巨兽",
        "漆黑海面横贯星空，鳞甲之下每次呼吸都令一座世界的潮汐倒转。",
        "没有兵器能轻易刺穿它的鳞，没有海能真正容下它。诸界相连只给了深渊更辽阔的水域。",
        "深渊王冠沉没，沸腾群海重新映出安静星辰。",
        "巨鳞缝隙里留下一枚盐白遗羽，靠近耳边便能听见海底沉重的心跳。",
    ),
    _disaster(
        "surtr",
        "flame_tyrant",
        DISASTER_ORIGIN_DOCUMENTED,
        "北欧神话火巨人苏尔特尔传说",
        "苏尔特尔·焚界者",
        "持燃世之剑守候终局的火巨人",
        "比太阳更亮的巨剑划破界壁，剑锋所指之处，空间先于草木开始燃烧。",
        "它并不憎恨世界，只负责在终局到来时点燃一切。错误的钟声让它提前拔出了剑。",
        "燃世巨剑化作暗红铁水，终局被重新推回遥远未来。",
        "冷却铁水中浮起一枚赤金遗羽，羽脉像一张尚未燃尽的世界地图。",
    ),
    _disaster(
        "nidhogg",
        "ancient_tree_king",
        DISASTER_ORIGIN_DOCUMENTED,
        "北欧神话啃噬世界树根的尼德霍格传说",
        "尼德霍格·蚀根黑龙",
        "从世界根系下方啃噬秩序的黑龙",
        "无数世界的根须同时枯黄，黑龙伏在根系交汇处，每一次咬合都让一段历史消失。",
        "它以腐朽与遗忘为食。世界越繁盛，根下堆积的旧死便越能养大它的饥饿。",
        "黑龙坠回根下，消失的年轮在树干上缓慢重现。",
        "腐叶间落下一枚墨绿遗羽，羽轴上生着一圈刚刚恢复的年轮。",
    ),
    _disaster(
        "hecatoncheires",
        "iron_titan",
        DISASTER_ORIGIN_DOCUMENTED,
        "古希腊神话百臂巨人传说",
        "百臂巨灵·群山投手",
        "以百只手臂同时投掷群山的泰坦",
        "百条巨臂伸出云外，每只手都抓着来自不同世界的一座山。",
        "它曾以群山帮助新神赢得战争，却在漫长看守中忘记战争已经结束。现在所有移动都被视作越狱。",
        "百座山峰同时落回原位，巨灵的手臂一条条隐入云后。",
        "碎石旋流中停着一枚灰蓝遗羽，羽片上压着百枚微小掌印。",
    ),
    _disaster(
        "starless_queen",
        "frost_queen",
        DISASTER_ORIGIN_ORIGINAL,
        "原创星界灾厄",
        "无星女王",
        "收藏熄灭星辰的最后一位君主",
        "黑裙女王乘无光王座降临，裙摆每掠过一处天空，群星便像名字一样被抹去。",
        "她的王国早已失去最后一颗恒星，于是她穿行诸界，确信只要所有天空同样黑暗，故国便不算毁灭。",
        "王座碎裂，所有被收藏的星光从她掌心飞回各自夜空。",
        "星尘聚成一枚纯黑遗羽，转动时会短暂显出无数已经归还的微光。",
    ),
    _disaster(
        "ashen_bell",
        "ash_phoenix",
        DISASTER_ORIGIN_ORIGINAL,
        "原创灰烬灾厄",
        "灰烬钟王",
        "每次敲钟都令一个时代提前结束的守钟者",
        "巨钟悬在破碎时间之上，披灰王者举起钟槌，诸界同时听见本不属于今日的丧音。",
        "他曾负责为旧纪元送终，却在自己的世界毁灭后再也等不到新纪元开始。于是钟声只剩结束。",
        "钟槌断裂，最后一声余响没有抵达任何世界。",
        "静止灰烬凝成一枚钟形遗羽，触碰时只能感到一声没有声音的震动。",
    ),
    _disaster(
        "thirteenth_gate",
        "final_guardian",
        DISASTER_ORIGIN_ORIGINAL,
        "原创界门灾厄",
        "第十三门守望者",
        "看守一扇从未被建造之门的无面骑士",
        "十二座界门依次开启后，虚空中浮出不存在的第十三扇门，无面骑士从门后策马而来。",
        "没有人知道门内封着什么。守望者只知道，凡是看见这扇门的人都已越过不应越过的边界。",
        "第十三门从门框中央向外消失，骑士连同最后一道马蹄声退回门后。",
        "空门留下的轮廓折成一枚苍白遗羽，羽心是一道无法穿过的细缝。",
    ),
)


__all__ = ["MAGIC_DISASTERS", "MAGIC_DISASTER_SOURCE_ID"]
